AWSTemplateFormatVersion: '2010-09-09'
Description: Pet Clinic
Resources:
  DeletePetByIDFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: delete
            Path: /pets
          Type: Api
      Handler: dynamo_pet_delete_by_id.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  GetPetByIDFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: get
            Path: /pets/{petId}
          Type: Api
      Handler: dynamo_pet_query_by_id.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  GetPetFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: get
            Path: /pets
          Type: Api
      Handler: dynamo_pet_query_all.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  GetPetImageFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: get
            Path: /pets/image/{petId}
          Type: Api
      Handler: dynamo_pet_get_image_s3.handler
      Policies:
      - AmazonDynamoDBFullAccess
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::xdr56yhn-aws-sam-petclinic-pics/*
        Version: '2012-10-17'
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  GetPetsByStatusFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: get
            Path: /pets/status/{status}
          Type: Api
      Handler: dynamo_pet_find_by_status.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  PostPetFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: post
            Path: /pets
          Type: Api
      Handler: dynamo_pet_create_record.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  PostPetInfoByIDFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: post
            Path: /pets/info
          Type: Api
      Handler: dynamo_pet_update_info.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  PostPetStatusByIDFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: post
            Path: /pets/status
          Type: Api
      Handler: dynamo_pet_update_status.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  PostUploadPetImageFunction:
    Properties:
      CodeUri: s3://xdr56yhn-aws-sam/638697ee0d1a8764d8b6b3bc1edd50b2
      Events:
        Inventory:
          Properties:
            Method: post
            Path: /pets/image/{petId}
          Type: Api
      Handler: dynamo_pet_upload_image_s3.handler
      Policies:
      - AmazonDynamoDBFullAccess
      - Statement:
        - Action:
          - s3:*
          Effect: Allow
          Resource: arn:aws:s3:::xdr56yhn-aws-sam-petclinic-pics/*
        Version: '2012-10-17'
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
